[build]
command = "npm run build"
publish = "public"

[dev]
command = "remix watch"
port = 3000

[functions]
included_files = ["templates/**"]

[[redirects]]
from = "/*"
status = 200
to = "/.netlify/functions/server"

[[headers]]
for = "/build/*"
[headers.values]
"Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
